name: retrofit_cli
description: Retrofit code generator.
version: 0.0.1-dev.01
homepage: https://github.com/luiscib3r/retrofit_cli
repository: https://github.com/luiscib3r/retrofit_cli
issue_tracker: https://github.com/luiscib3r/retrofit_cli/issues

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  args: ^2.3.1
  equatable: ^2.0.5
  json_annotation: ^4.8.0
  mason: ^0.1.0-dev.41
  mason_logger: ^0.2.4
  path: ^1.8.3
  pub_updater: ^0.2.4
  pubspec_parse: ^1.2.1
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0

executables:
  retrofit_cli:
