name: {{name.snakeCase()}}_api
description: {{name.pascalCase()}} Api Package.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dio: ^5.0.0
  equatable: ^2.0.5
  json_annotation: ^4.8.0
  retrofit: ^4.0.1

dev_dependencies:
  build_runner: ^2.0.0  
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  retrofit_generator: ^5.0.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0+1
